In [97]:
import numpy as np



# Question 1


scores = np.array([[80, 70, 90],[60, 85, 75], 
                  [95, 88, 92], [70, 60, 65]])
print("Student scores in a matrix:", scores)

Student scores in a matrix: [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


In [98]:
print("Total score for each (student_1, student_2, student_3, student_4) :", np.sum(scores, axis=1))  

Total score for each (student_1, student_2, student_3, student_4) : [240 220 275 195]


In [99]:
scores = scores.copy()
scalar_math = 2

scores[:, 0] = scalar_math * scores[:, 0]
print(scores)

[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [100]:
print("Average score for each (Math, English, Science) :", np.mean(scores, axis=0))  

Average score for each (Math, English, Science) : [152.5   75.75  80.5 ]


In [101]:
average_score = np.mean(scores, axis = 0)

weight_vector = np.array([0.5, 0.3, 0.2])
final_grade = weight_vector * average_score
print("The final_grades:", final_grade)

The final_grades: [76.25  22.725 16.1  ]


In [103]:
scores

array([[160,  70,  90],
       [120,  85,  75],
       [190,  88,  92],
       [140,  60,  65]])

In [104]:
student_1_score = scores[0:1]
student_2_score = scores[1:2]

print("Student_1 Score vector:",student_1_score)
print("\n")
print("Student_2 Score vector:",student_2_score)

compare_scores = student_1_score - student_2_score
print("\n")
print("comparing student (1 & 2) vector score", compare_scores)

Student_1 Score vector: [[160  70  90]]


Student_2 Score vector: [[120  85  75]]


comparing student (1 & 2) vector score [[ 40 -15  15]]


In [105]:
# Question 2


new_scores = np.array([[82, 71, 77, 55],[50, 45, 79, 82], 
                  [59, 68, 72, 53], [30, 70, 55, 64], [72, 83, 65, 87]])
print("Student scores in a matrix:", new_scores)

Student scores in a matrix: [[82 71 77 55]
 [50 45 79 82]
 [59 68 72 53]
 [30 70 55 64]
 [72 83 65 87]]


In [106]:
new_scores.shape

(5, 4)

In [107]:
print("Total score for each (student_1, student_2, student_3, student_4, student_5) :", np.sum(new_scores, axis=1))  

Total score for each (student_1, student_2, student_3, student_4, student_5) : [285 256 252 219 307]


In [108]:
print("Average score for each (Math, English, Science, chemistry) :", np.mean(new_scores, axis=0)) 

Average score for each (Math, English, Science, chemistry) : [58.6 67.4 69.6 68.2]


In [109]:
new_scores = new_scores.copy()
scalar_science = 3

new_scores[:, 2] = scalar_science * new_scores[:, 2]
print(new_scores)




[[ 82  71 231  55]
 [ 50  45 237  82]
 [ 59  68 216  53]
 [ 30  70 165  64]
 [ 72  83 195  87]]


In [110]:
average_score_2 = np.mean(new_scores, axis = 0)

weight_vector_2 = np.array([0.4, 0.2, 0.3, 0.1])
final_grade_2 = weight_vector_2 * average_score_2
print("The final_grades:", final_grade_2)

The final_grades: [23.44 13.48 62.64  6.82]


In [111]:
student_3_score = new_scores[2:3]
student_4_score = new_scores[3:4]

print("Student_3 Score vector:",student_3_score)
print("\n")
print("Student_4 Score vector:",student_4_score)

compare_scores_2 = student_3_score - student_4_score
print("\n")
print("comparing student (3 & 4) vector score", compare_scores_2)

Student_3 Score vector: [[ 59  68 216  53]]


Student_4 Score vector: [[ 30  70 165  64]]


comparing student (3 & 4) vector score [[ 29  -2  51 -11]]


In math - student 3 performs better
In english - student 4 performs better
In Science - student 3 performs better
In chemistry - student 4 performs better
