In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

Matplotlib is building the font cache; this may take a moment.


In [ ]:
# check mumpy version

print(f"Numpy version: {np.__version__}")

# Display setting for cleaner output
np.set_printoptions(precision=3, suppress=True)
6d

Numpy version: 2.3.2


In [5]:
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], 
                [4, 5, 6]])

arr3d = np.array([[1, 2], [3, 4], 
                 [5, 6], [6, 7]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[1 2]
 [3 4]
 [5 6]
 [6 7]]


In [7]:
zeros = np.zeros((3, 4)) # 3 rows 4 columns memory efficient
ones = np.ones((2, 3, 4))  # 2-layers, 3 rows, 4 columns memory efficient
empty = np.empty((2, 2)) # faster than zeros/ones but contains random values(garbage values)normally used to fill array 

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)


Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[2.669e+092 4.272e+180]
 [3.532e+010 3.787e+039]]


In [8]:
range_arr = np.arange(0, 10, 2) # works like a range in python(start, stop, step)
print("Range array:", range_arr)

linspace_arr = np.linspace(0, 1, 5) # evenly spaced values from 0 to 1 and the values should be 5.
print("Linspace array:", linspace_arr)

logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr) # similar to linspace but it is used for scientific data and it is logarithmically spaced


Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [9]:
identity = np.eye(4)   # identity matrix

diagonal = np.diag((1, 2, 3, 4)) # This put this value on a diagonal

full_arr = np.full((3, 3), 7)  # This is 3 by 3 array filled with 7


print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [13]:
int_arr = np.array([1, 2, 3], dtype=np.int32) # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64) # 64-bit floats(double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_) # boolean values

# Type conversion
converted = int_arr.astype(np.float32) # convert to 32-bit float

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

#memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element") # .itemsize to check the memory usage 
print(f"float64 uses {float_arr.itemsize} bytes per element")


# int8: 1 byte, the range is between -128 to 127

# int32: 4 bytes, the range is between - or + 2 billion

# float32: 4 bytes, this is approximately 7 decimal digits precision

# float64: 8 bytes, this is approximately 15 decimal digits precision

# it is better to choose smaller types to save memory, larger types for precision


Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


In [14]:
# Array properties and attributes

arr = np.random.randn(3, 4, 5) # 3D array 3 layers, 4 -rows, 5- columns

print("Shape:", arr.shape) # dimensional shape (layers, rows, columns)
print("Size:", arr.size) # Total number of elements (3 x 4 x 5 = 60)
print("Ndim:", arr.ndim) # number of dimensions (3D in this case)
print("Dtype:", arr.dtype)  # usually float64 for random numbers
print("Itemsize", arr.itemsize) # 8 bytes for float64

# Total memory usage in bytes
print("Memory usage:", arr.nbytes, "bytes") # size x itemsize
print("Memory usage:", arr.nbytes / 1024, "KB") # Convert to KB

Shape: (3, 4, 5)
Size: 60
Ndim: 3
Dtype: float64
Itemsize 8
Memory usage: 480 bytes
Memory usage: 0.46875 KB


In [15]:
# Array.indexing and Slicing

arr1d = np.array([10, 20, 30, 40, 50])

print("First element:", arr1d[0])     # Index 0: 10
print("Last element:", arr1d[-1])     # Negative indexing: 50  
print("Slice [1:4]:", arr1d[1:4])     # Elements 1, 2, 3: [20, 30, 40]
print("Every 2nd element:", arr1d[::2])  # Step of 2: [10, 30, 50]

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every 2nd element: [10 30 50]


In [16]:
# 2D array indexing - row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access specific element: [row, column]
print("Element at row 1, column 2:", arr2d[1, 2])

# Access entire rows or columns
print("First row:", arr2d[0, :])               # All columns of row 0
print("Second column:", arr2d[:, 1])           # All rows of column 1


# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n", arr2d[1:3, 1:3])

Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


In [17]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4]) # select elements at position 0, 2, 4
print("Fancy indexing:", arr[indices])

Fancy indexing: [10 30 50]


In [18]:
# This is much more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1])  # Can repeat and reorder
print("Random order:", arr[random_indices])   # [50, 20, 40, 20]

Random order: [50 20 40 20]


In [19]:
# 2D fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3, 4)  # 3x4 array: [[0,1,2,3], [4,5,6,7], [8,9,10,11]]
print("Original 2D array:\n", arr2d)

# Select elements at (row, col) pairs: (0,1) and (2,3)
rows = np.array([0, 2])
cols = np.array([1, 3])
print("Elements at (0,1) and (2,3):", arr2d[rows, cols])  # [1, 11]

# Select entire rows using fancy indexing
selected_rows = arr2d[[0, 2], :]  # Rows 0 and 2, all columns
print("Selected rows:\n", selected_rows)

Original 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements at (0,1) and (2,3): [ 1 11]
Selected rows:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [20]:
# Start with a 1D array
arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original 1D array:", arr)

# Reshape to 2D: 3 rows × 4 columns
reshaped_2d = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape to 3D: 2 layers × 2 rows × 3 columns  
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 to let NumPy calculate one dimension automatically
auto_reshape = arr.reshape(4, -1)  # 4 rows, NumPy calculates columns
print("Auto-reshaped to 4x?:\n", auto_reshape)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Auto-reshaped to 4x?:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
