1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array

In [ ]:
import random
import numpy as np
#number= random.randint(1, 50)
arr6d = np.random.randint(1, 50, size= (6, 6))
arr6d

array([[46, 27, 15, 46,  6, 10],
       [24, 36, 41, 46,  6,  7],
       [46, 11,  8, 49,  3, 46],
       [21, 48,  8, 38, 28, 42],
       [20, 45, 12,  7,  8,  3],
       [47, 37, 14, 44, 48, 40]], dtype=int32)

2.  Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array


In [14]:
print("The first two rows:", arr6d[:2])
print("\n")
print("The last three columns:", arr6d[:,-3:])
slicing = arr6d[:,-3:]
even_numbers = slicing[slicing % 2 == 0]
print("\n")
print("Even numbers in the slicing matrix :", even_numbers)


The first two rows: [[46 27 15 46  6 10]
 [24 36 41 46  6  7]]


The last three columns: [[46  6 10]
 [46  6  7]
 [49  3 46]
 [38 28 42]
 [ 7  8  3]
 [44 48 40]]


Even numbers in the slicing matrix : [46  6 10 46  6 46 38 28 42  8 44 48 40]


 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D


In [7]:
reshaped_arr6d = arr6d.reshape(3, 2, 6)
print("Resshape array:", reshaped_arr6d)
print("\n")
print("Flattened the reshaped:", reshaped_arr6d.flatten())

Resshape array: [[[46 27 15 46  6 10]
  [24 36 41 46  6  7]]

 [[46 11  8 49  3 46]
  [21 48  8 38 28 42]]

 [[20 45 12  7  8  3]
  [47 37 14 44 48 40]]]


Flattened the reshaped: [46 27 15 46  6 10 24 36 41 46  6  7 46 11  8 49  3 46 21 48  8 38 28 42
 20 45 12  7  8  3 47 37 14 44 48 40]


 4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10

In [9]:
arr4d = np.random.randint(10, 40, size= (4, 4))
print("4 by 4  Identity matrix:", arr4d)
print("\n")
num = np.arange(10, 40, 10)
np.fill_diagonal(arr4d, num)
print(arr4d)


4 by 4  Identity matrix: [[18 27 25 20]
 [16 11 32 13]
 [33 17 27 27]
 [21 26 27 23]]


[[10 27 25 20]
 [16 20 32 13]
 [33 17 30 27]
 [21 26 27 10]]


5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [13]:
matrix_A = np.random.randint(1, 10, size= (3, 4))
matrix_B = np.random.randint(1, 10, size=(4, 3))
print("Matrix A:", matrix_A)
print("\n")
print("Matrix B:", matrix_B)
print("\n")
mat_mult = np.dot(matrix_A , matrix_B)
print("Matrix multiplication:", mat_mult)

Matrix A: [[8 3 4 5]
 [6 1 3 2]
 [2 9 9 5]]


Matrix B: [[3 6 3]
 [5 3 9]
 [8 5 3]
 [1 7 8]]


Matrix multiplication: [[ 76 112 103]
 [ 49  68  52]
 [128 119 154]]


 6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1

In [ ]:
import numpy as np

def numpy_2D(a):
    result = a.copy()
    result[a % 2 == 0] == result[a % 2 == 0] ** 2
    result[a % 2 != 0] = -1
    return result

#def get_userinput()

#arr2d = np.random.randint(1, 10, size= (2, 2))
rows = int(input("Enter the number of rows:"))
columns = int(input("Enter the number of columns:"))

if rows <= 0  or columns <= 0:
        raise ValueError
input_array = []
print(f"Enter {rows * columns} integer for {rows} x {columns} array (row by column)")
for i in range (rows):
    rows = []
    for j in range (columns):
        while True:
            try:
                element = input(f"Enter element at position {i}{j}:")
                rows.append(element)
                break
            except ValueError:
                print("Please enter a valid integer")
                input_array.append(rows)

arr = np.array(input_array)
output = numpy_2D(arr)
print(output)




