#### 1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array

In [ ]:
import random
import numpy as np

arr6d = np.random.randint(1, 50, size= (6, 6))
arr6d

array([[26, 19, 16, 24, 15,  5],
       [33, 45, 28, 14, 18, 20],
       [41, 10,  7,  8, 28,  3],
       [30, 18,  3, 19, 20, 15],
       [37, 24, 49, 25, 21, 25],
       [ 9, 40, 19, 31, 41, 46]], dtype=int32)

#### 2.  Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array


In [3]:
print("The first two rows:", arr6d[:2])
print("\n")
print("The last three columns:", arr6d[:,-3:])

even_numbers = arr6d[arr6d % 2 == 0]
print("\n")
print("Even numbers in the matrix :", even_numbers)


The first two rows: [[26 19 16 24 15  5]
 [33 45 28 14 18 20]]


The last three columns: [[24 15  5]
 [14 18 20]
 [ 8 28  3]
 [19 20 15]
 [25 21 25]
 [31 41 46]]


Even numbers in the matrix : [26 16 24 28 14 18 20 10  8 28 30 18 20 24 40 46]


#### 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D


In [9]:
reshaped_arr6d = arr6d.reshape(3, 2, 6)
print("Resshaped array:\n", reshaped_arr6d)
print("\nFlattened the reshaped array to 1D:\n", reshaped_arr6d.flatten())

Resshaped array:
 [[[26 19 16 24 15  5]
  [33 45 28 14 18 20]]

 [[41 10  7  8 28  3]
  [30 18  3 19 20 15]]

 [[37 24 49 25 21 25]
  [ 9 40 19 31 41 46]]]

Flattened the reshaped array to 1D:
 [26 19 16 24 15  5 33 45 28 14 18 20 41 10  7  8 28  3 30 18  3 19 20 15
 37 24 49 25 21 25  9 40 19 31 41 46]


#### 4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10

In [14]:
arr4d = np.random.randint(1, 50, size= (4, 4))
print("4 by 4 Identity matrix:\n", arr4d)
num = np.arange(10, 40, 10)
np.fill_diagonal(arr4d, num)
print("\n Final output:\n",arr4d)


4 by 4 Identity matrix:
 [[27 13 35 14]
 [40 46 27 10]
 [16 39 32 33]
 [28 42 29 26]]

 Final output:
 [[10 13 35 14]
 [40 20 27 10]
 [16 39 30 33]
 [28 42 29 10]]


5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [16]:
matrix_A = np.random.randint(1, 10, size= (3, 4))
matrix_B = np.random.randint(1, 10, size=(4, 3))
print("Matrix A:\n", matrix_A)
print("\n")
print("Matrix B:\n", matrix_B)
print("\n")
mat_mult = np.dot(matrix_A , matrix_B)
print("Matrix multiplication:\n", mat_mult)

Matrix A:
 [[7 5 5 8]
 [9 9 6 7]
 [4 7 1 5]]


Matrix B:
 [[1 1 4]
 [7 7 9]
 [9 5 1]
 [6 3 7]]


Matrix multiplication:
 [[135  91 134]
 [168 123 172]
 [ 92  73 115]]


 6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1

In [19]:
import numpy as np

def numpy_2D(a):
    result = a.copy()
    # square even number and replace odd numbers with -1
    result = np.where(a % 2 == 0, a ** 2, -1)
    return result

# take user input for 2D array
rows = int(input("Enter the number of rows:"))
columns = int(input("Enter the number of columns:"))

# validate user input 
if rows <= 0  or columns <= 0:
        raise ValueError
# create empty list to store array element
input_array = []

# this shows array elements from the user
print(f"Enter {rows * columns} integer for {rows} x {columns} array (row by column)")
for i in range (rows):
    rows = []
    for j in range (columns):
        while True:
            try:
                element = int(input(f"Enter element at position [{i}][{j}]:"))
                rows.append(element)
                break
            except ValueError:
                print("Please enter a valid integer")
    input_array.append(rows)


# convert list to  numpy array
a = np.array(input_array)

# applying the function
output = numpy_2D(a)
# printing the original entry and the final output after applying the function
print("original array:\n", a)
print("\nnew array:\n", output)


# def array_2D():
#     row = int(input("Enter number for row: "))
#     column = int(input("Enter number for column: "))

#     arr  = np.arange(row * column).reshape(row, column)
#     new_arr = np.where(arr % 2 == 0, arr ** 2, -1)
#     print(new_arr)




Enter 4 integer for 2 x 2 array (row by column)
original array:
 [[1 2]
 [3 4]]

new array:
 [[-1  4]
 [-1 16]]
